// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqeXfN_E1zZ8ZpfgKOyCiErkJLlkOF4Gs',
    appId: '1:103904022357:web:f3fdf6c75dfcb1b111e9dc',
    messagingSenderId: '103904022357',
    projectId: 'ddosprotectionapp',
    authDomain: 'ddosprotectionapp.firebaseapp.com',
    storageBucket: 'ddosprotectionapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdBVM1YnxwyOTpGfR26Psi0fbZa031pIw',
    appId: '1:103904022357:android:21e3b2db43faae8611e9dc',
    messagingSenderId: '103904022357',
    projectId: 'ddosprotectionapp',
    storageBucket: 'ddosprotectionapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFuErzPhnCxPjTBZtfQZbf3y3tLfbawhQ',
    appId: '1:103904022357:ios:d92f9009dac5061711e9dc',
    messagingSenderId: '103904022357',
    projectId: 'ddosprotectionapp',
    storageBucket: 'ddosprotectionapp.appspot.com',
    iosBundleId: 'com.example.ddosProtectionApp',
  );
}
